# this relies on arc64-dev branch of toolchain repo

# you must create "./tmp" dir explicitly
set tmpdir "./tmp"
set srcdir "$env(COMPSRC)/gcc/gcc/testsuite"

set target_triplet arc64-unknown-elf
set target_alias arc64-elf

set tool gcc
set target_list arc-sim-nsimdrv

set CFLAGS ""
set CXXFLAGS ""

set verbose 0

set arc_board_dir "$env(COMPSRC)/toolchain"
if ![info exists boards_dir] {
    lappend boards_dir "$arc_board_dir/dejagnu"
    lappend boards_dir "$arc_board_dir/dejagnu/baseboards"
} else {
    set boards_dir "$arc_board_dir/dejagnu"
    lappend boards_dir "$arc_board_dir/dejagnu/baseboards"
}
