#!/bin/bash

opts=$(mcpu-to-cpu-opts --elf-file-path $1 --print-nsim-opts)

nsimdrv \
    -on nsim_isa_enable_timer_0 \
    -on nsim_isa_enable_timer_1 \
    -off invalid_instruction_interrupt \
    -off memory_exception_interrupt \
    -prop=nsim_emt=1 \
    ${opts} \
    "$@"
