#!/bin/bash

qemu_args=()
while [[ "$1" != "" ]]
do
    case "$1" in
	-Wq,*) qemu_args+=("$echo "$1" | cut -d, -f2-)");;
	*) break;;
    esac
    shift
done

xlen="$(readelf -h $1 | grep 'Class' | cut -d: -f 2 | xargs echo | sed 's/^ELF//')"

case "$xlen" in
    64) qemu="64";;
    *) qemu="";;
esac

qemu-arc$qemu -cpu ${QEMU_CPU} -R 3G "${qemu_args[@]}" -L ${ARC_SYSROOT} "$@"
